changelog:
  exclude:
    labels:
      - ignore-for-release-notes
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Bugfixes 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
